# NumPy   Arrays

In [8]:
my_list= [2,3,5]

In [9]:
my_list

[2, 3, 5]

In [10]:
import numpy as np

In [11]:
np.array(my_list)

array([2, 3, 5])

In [12]:
arr = np.array(my_list)

In [13]:
arr

array([2, 3, 5])

In [14]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(7)

array([0.89916265, 0.92125625, 0.99017338, 0.92906373, 0.59821223,
       0.84987915, 0.96200974])

In [24]:
np.random.rand(7,3)

array([[0.50610806, 0.96514705, 0.7209875 ],
       [0.58272283, 0.18322574, 0.33954481],
       [0.40302737, 0.77231112, 0.7715906 ],
       [0.38623924, 0.1145975 , 0.72831714],
       [0.57423901, 0.5544781 , 0.08663015],
       [0.02558586, 0.36428096, 0.88689724],
       [0.78190105, 0.41115295, 0.92751587]])

In [25]:
np.random.randn(7)

array([ 1.2718023 ,  0.39341082,  0.21916644, -0.81601915,  1.04437628,
       -1.157467  ,  0.46355365])

In [26]:
np.random.randint(1,20,5)

array([ 1, 12, 19,  4,  7])

In [29]:
ads = np.arange(20)

In [30]:
ads

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
rads = np.random.randint(0,50,10)

In [32]:
rads

array([ 9, 47, 24, 42, 32, 25, 19, 29, 48,  5])

In [35]:
ads.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
ads.max()

19

In [37]:
ads.min()

0

In [38]:
ads

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
ads.argmax()

19

In [40]:
ads.argmin()

0

In [41]:
ads.shape

(20,)

In [ ]:
cs = ads.reshape(4)