# Numpy Indexing & Selection

In [3]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8] #printing 8th index indexing start at 0 in numpy

8

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[0:6] 

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]
#the 6th element in the array, but it is located at index 5
#(just like a normal Python list, indexing starts at zero in Numpy arrays). 
#Therefore, the arr[5:] notation actually grabs everything starting with the 
#index 5, not everything beyond index 5

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5]=100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Numpy Operations

Array with array   
array with scalars  
Universal Array Functions

In [3]:
import numpy as np

In [4]:
new = np.arange(0,11)

In [5]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
new + new 


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
new - new 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
new * new 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [13]:
new / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
new + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
new * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
new ** 3  # cube of number

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [17]:
np.sqrt(new)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [19]:
np.exp(new)   # e ( power) the value of array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [22]:
np.max(new)   # or we can write new.max()

10

In [21]:
new.max()

10

In [23]:
np.sin(new)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [26]:
np.log(new[1:]) # we start from 1 coz log 0 is infinity error

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])